/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorPick: typeof import('./src/components/tools/ColorPick.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FlootBar: typeof import('./src/components/Base/FlootBar.vue')['default']
    HeadBar: typeof import('./src/components/Base/HeadBar.vue')['default']
    IEpAddBell: typeof import('~icons/ep/add-bell')['default']
    IEpAddIphone: typeof import('~icons/ep/add-iphone')['default']
    IEpAddIPhone: typeof import('~icons/ep/add-i-phone')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAddUser: typeof import('~icons/ep/add-user')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpCircleClose: typeof import('~icons/ep/circle-close')['default']
    IEpIphone: typeof import('~icons/ep/iphone')['default']
    IEpKey: typeof import('~icons/ep/key')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    KindsTitle: typeof import('./src/components/Base/KindsTitle.vue')['default']
    NavModel: typeof import('./src/components/Base/navModel.vue')['default']
    RecommendCover: typeof import('./src/components/MusicCover/recommendCover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/Base/SideBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
